CREATE TABLE OEMEMBER (
	ONUM VARCHAR2(20) PRIMARY KEY,
	ONAME VARCHAR2(200) NOT NULL,
	OID  VARCHAR2(300) NOT NULL,
	OPW  VARCHAR2(300) NOT NULL,
	OHP  VARCHAR2(16) NOT NULL,
	OGENDER VARCHAR2(1) NOT NULL,
	OZONECODE VARCHAR2(6) NOT NULL,
	OROAD VARCHAR2(500),
	OROADDETAIL VARCHAR2(500),
	OJIBUN VARCHAR2(500),
	MASTER VARCHAR2(1) NOT NULL,
	INSERTDATE DATE,
	UPDATEDATE DATE,
	DELETEYN VARCHAR2(1),
	OEMAIL VARCHAR2(100)
);

SELECT * FROM OEMEMBER;

CREATE TABLE OEBOARD (
	BNUM VARCHAR2(20) PRIMARY KEY,
	OID VARCHAR2(300) NOT NULL,
	BTITLE VARCHAR2(500) NOT NULL,
	BPHOTO VARCHAR2(300),
	BCONTENT VARCHAR2(2000),
	BPRICE VARCHAR2(100) NOT NULL,
	INSERTDATE DATE,
	UPDATEDATE DATE,
	DELETEYN VARCHAR2(1),
	BPW VARCHAR2(300),
	BHIT NUMBER DEFAULT 0,
	OENUM VARCHAR2(20)
);

SELECT * FROM OEBOARD ORDER BY 1;

CREATE TABLE OELIKE (
	OLNUM VARCHAR2(20) PRIMARY KEY,
	BNUM VARCHAR2(20) NOT NULL,
	ONUM VARCHAR2(20) NOT NULL,
	LIKECNT NUMBER DEFAULT 0,
	INSERTDATE DATE,
	UPDATEDATE DATE,
	DELETEYN VARCHAR2(1)
);

CREATE TABLE OECOM(
	CNUM VARCHAR2(20) PRIMARY KEY,
	BNUM VARCHAR2(20) NOT NULL,
	OID VARCHAR2(20) NOT NULL,
	CCONTENT VARCHAR2(2000),
	INSERTDATE DATE,
	DELETEYN VARCHAR2(1)
);

SELECT * FROM OECOM;

CREATE TABLE OECART(
	OCNUM VARCHAR2(20) PRIMARY KEY,
	OID VARCHAR2(20), 
	BNUM VARCHAR2(20), 
	OLNUM VARCHAR2(20),
	DELETEYN VARCHAR2(1)
);

SELECT * FROM OECART;